name: Auto Package Helper
on:
  workflow_dispatch:
  push:
    tags:
    - "v*.*.*"

jobs:
  build-py37:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Cache Python packages
        uses: actions/cache@v2
        if: startsWith(runner.os, 'Windows')
        id: cache-pip
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Install Python lib
        run: |
          pip install -r requirements.txt

      - name: Package to exe
        run: pyinstaller -F .\BackgroundMuter.py

      - name: Release files
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/BackgroundMuter.exe

